url: "https://brandonpow1.github.io"
baseurl: "magetale-site"
title: "A Mage Tale"

plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag

postcss:
  cache: false
  
sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]
